FROM openjdk:8
WORKDIR /target
COPY . /target/
#  ADD /bear-dispenser-api-0.0.1-SNAPSHOT.jar //
#  ENTRYPOINT java -jar /bear-dispenser-api-0.0.1-SNAPSHOT.jar
CMD [ "java", "-jar", "bear-dispenser-api-0.0.1-SNAPSHOT.jar" ]