version: "3"
services:
  dbservice:
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - ./data:/var/lib/mysql
    
    ports:
      - 3307:3306
  
    networks:
      - beerapp

  appservice:
    build: ""
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/beer_dispensery?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root

    ports:
      - 8085:9292

    networks:
      - beerapp
       
networks:
  beerapp: